"""Export native Misc Fixed 7x14 glyphs, without scaling or resampling."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'fonts/7x14.bdf'
DESTINATION = ROOT / 'include/title_font.h'


def read_glyphs():
    result = {}
    source = SOURCE.read_text(encoding='ascii')
    for block in re.findall(r'STARTCHAR .*?\n(.*?)ENDCHAR', source, re.S):
        cp = int(re.search(r'^ENCODING (\d+)$', block, re.M)[1])
        if not (32 <= cp < 127 or 0x400 <= cp < 0x530):
            continue
        assert re.search(r'^DWIDTH 7 0$', block, re.M)
        assert re.search(r'^BBX 7 14 0 -2$', block, re.M)
        rows = [int(row, 16) for row in block.split('BITMAP\n')[1].split()]
        assert len(rows) == 14 and all(row & 1 == 0 for row in rows)
        result[cp] = rows
    assert all(ord(ch) in result for ch in 'ҐґЄєІіЇї')
    assert all(cp in result for cp in range(32, 127))
    return dict(sorted(result.items()))


if __name__ == '__main__':
    glyphs = read_glyphs()
    lines = [
        '#pragma once', '#include <Arduino.h>', '',
        '// Generated by scripts/make-title-font.py from fonts/7x14.bdf.',
        '// Misc Fixed, public domain: "Share and enjoy." Native 7x14 pixels.',
        'struct TitleGlyph { uint16_t codepoint; uint8_t rows[14]; };',
        'static const TitleGlyph TITLE_GLYPHS[] PROGMEM = {',
    ]
    for cp, rows in glyphs.items():
        lines.append('  {0x%04X, {%s}},' % (cp, ', '.join('0x%02X' % row for row in rows)))
    lines += [
        '};',
        f'constexpr uint16_t TITLE_GLYPH_COUNT = {len(glyphs)};',
        f'constexpr uint16_t TITLE_FALLBACK_INDEX = {list(glyphs).index(ord("?"))};',
        '',
    ]
    DESTINATION.write_text('\n'.join(lines), encoding='ascii')
    print(f'Exported {len(glyphs)} native glyphs ({len(glyphs) * 16} flash bytes).')
